spring.application.name=rewards-api
server.port=8080
spring.jackson.datatype.datetime.write-dates-as-timestamps=false
management.endpoints.web.exposure.include=health,info,metrics
management.info.env.enabled=true
info.app.name=Rewards API
info.app.description=Project used for Rewards API Integration
info.app.version=1.0.0
info.app.developer=Sajith V J
